--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/Lifespan
branches:
  - master
projects:
  PaymentPool:
    icon: "icon.png"
    lint:
      phpstan: false
    libs:
      - src: blugin/libcommand/libcommand
        version: ^1.3.3
      - src: blugin/libtranslator/libtranslator
        version: ^1.0.5
      - src: Blugin/virions/SingletonTrait
        version: ^1.0.0
...
